- requirements.txt
- setup.py
This PR will allow people to install the requirements with `pip install -r requirements.txt` as well as installing the source dist with `pip`.
I tried this and all seems to work:
```shell
mkvirtualenv TMP --python=/usr/bin/python2
python setup.py sdist
cd dist
pip install --process-dependency-links odm2api-0.1.tar.gz
```
Note that `--process-dependency-links` seems to be deprecated:
Dependency Links processing has been deprecated with an accelerated time schedule and
will be removed in pip 1.6.
Not sure how to solve that.  I read a few threads that suggests this it won't be removed...
PS: Note that I am using the forked `v0.7.3` tag for `geoalchemy` on both the requirements file and on `setup.py`.  We can changed that to accept any future version, but I thought that this is "safer" for …
> Fix requirement file

- .gitignore
- Examples/Sample.py
- odm2api/ODM2/models.py
- odm2api/ODM2/services/createService.py
- odm2api/ODM2/services/readService.py
- odm2api/base.py
I have added inheritance, for results and sampling features, and I have tested it for both creation and reading. I was also able to add an init function to the base inherited class
> Addinheritance

- README.md
This PR only adds the Travis-CI badge in the GitHub front page (README.md).
It should help us to keep track of the tests.
@sreeder it seems that AppVeyor is running on your account. Can you get the badge URL for us? I can add it in this PR too.
- go to  https://ci.appveyor.com/project/sreeder/odm2pythonapi `setting`
- `Badges`
- copy-and-paste the `Sample markdown code`
> Add Travis-CI badge

- odm2api/ODM2/services/readService.py
Without this, I am getting error when querying Processing Levels using ids.
```python
>>> read.getProcessingLevels(ids=[1,2])
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-41-789bf4c34817> in <module>()
----> 1 read.getProcessingLevels(ids=[1,2])
/root/miniconda/envs/iTEST/lib/python2.7/site-packages/odm2api/ODM2/services/readService.pyc in getProcessingLevels(self, ids, codes)
257         """
258         q = self._session.query(ProcessingLevels)
--> 259         if ids: q = q.filter(ProcessingLevels.ProcessingLevels.in_(ids))
260         if codes: q = q.filter(ProcessingLevels.ProcessingLevelCode.in_(codes))
261 
AttributeError: type object 'ProcessingLevels' has no …
```
> fix getprocessinglevels to use id filter

- odm2api/ODM2/models.py
- odm2api/base.py
Rename PersonObj in Annotations. It should be named the same thing as the ID, which is AnnotatorID, so I have renamed it to AnnotatorObj. 
I checked the other objects to make sure there were not any other objects that had been missed when we renamed a while ago, and I didn't find anything.
> Rename Reference Object

- requirements.txt
- setup.py
This PR partially addresses https://github.com/ODM2/ODM2PythonAPI/issues/59#issuecomment-286564392
Note that PR https://github.com/ODM2/ODM2PythonAPI/pull/58 (mentioned in https://github.com/ODM2/ODM2PythonAPI/issues/59) was merged but https://github.com/geoalchemy/geoalchemy/pull/42 was not. It seems that if the path is to remove `geoalchemy` https://github.com/geoalchemy/geoalchemy/pull/42 will need to be re-written or just closed.
I could not find any other code reference to `geoalchemy` in master. I am unsure of the status on the multiple branches. BTW that many branches put a really high bar to get third party contributions to the code. I would be nice to reduce the development to `master` and eliminate the branches to temporary work on active PRs or stable releases.
I could not get …
> Remove geoalchemy dep

- .travis.yml
Using option 1 from https://github.com/ODM2/ODM2PythonAPI/issues/88 to "fix" Travis-CI for now and assess the real failures.
> pin Travis-CI image

- tests/test_odm2/test_readservice.py
This is a patch for assertion on `resapi`. A syntax sugar as discussed [here](https://github.com/ODM2/ODM2PythonAPI/pull/92#discussion_r133334453)
> Assert on any nulls

- odm2api/ODM2/services/readService.py
This PR addresses #95. It joins the necessary table to `Affiliations` table so that filter can actually occur. I have tested it and it seems to work.
> Fix person and organization filter for affiliations

- odm2api/ODM2/services/readService.py
This PR improves the docstring for `getAffiliations` to follow the numpy/scipy documentation standard. If you have suggestions of better wordings, please let me know. This relates to #97.
> Improve getAffiliation docstring to follow numpy/scipy documentation

- docs/source/conf.py
- docs/source/modules.rst
> add napoleon ext

- .travis.yml
> Use latest Travis-CI image.

- docs/source/conf.py
- docs/source/index.rst
- docs/source/models.rst
- docs/source/odm2models.rst
- odm2api/ODM2/models.py
This PR adds summary of the Core ODM2 Models.
> Add ODM2 Models Core Index

- docs/source/contribute.rst
- docs/source/index.rst
This PR creates a small documentation page that summarizes discussion on #106.
> Add documentation about how to contribute

- docs/source/contribute.rst
> Fix reST syntax.

- odm2api/ODM2/services/readService.py
This PR addresses #128. It also update the docstring to follow our convention.
> Fix Processing Levels code and docstring

- odm2api/ODM2/services/readService.py
Additionally added ability to filter by SamplingFeatureTypeCV as per Mauriel's request.
> Fixed getSamplingFeatureDatasets issue #130

- odm2api/ODM2/models.py
This is the same exact changes by @miguelcleon on PR #133. Just cleaner without the `.travis.yml` changes.
From @miguelcleon:
see that the first one, this is caused by Dataloggerfiles model, mapping to the wrong column within the database: https://github.com/ODM2/ODM2PythonAPI/blob/master/odm2api/ODM2/models.py#L458.
For the second one, measurementequation is indeed misspelled: https://github.com/ODM2/ODM2PythonAPI/blob/master/odm2api/ODM2/models.py#L514.
also 
found two more problems with dataloggerfiles model 
There is no column `dataloggeroutputfiledescription` instead it is `dataloggerfiledescription`
https://github.com/ODM2/ODM2PythonAPI/blob/master/odm2api/ODM2/models.py#L460
There is no column `dataloggeroutputfilelink` instead it is `dataloggerfilelink` …
> Error in DataLoggerFiles and DataLoggerFileColumns #132

- odm2api/ODM2/services/readService.py
This PR addresses #127. It changes the lowercase dataframe columns to the same cases as the model colump properties.
> Fix getresultvalues

- odm2api/ODM2/services/readService.py
This PR addresses #115. I simply put warnings to avoid breaking the API. All older code that uses the builtin arguments should still work.
> Fix builtins

- odm2api/ODM2/services/readService.py
Missed the builtins `type` in `getCVs` function. This should be the last ones, according to travis-CI.
> Missed builtin, should be last one

- odm2api/ODM2/services/readService.py
While working on the `odm2restapi`, I noticed that `getResults` was returning nothing when `sfid` is `None`, so this should fix that and `getResults` should return all results when `sfid` is `None`.
> Allow sfid to be None to work with older code

- odm2api/ODM2/services/readService.py
This PR Addresses https://github.com/ODM2/ODM2PythonAPI/issues/127#issuecomment-356519409. Now `getResultValues` and `getDatasetsValues` have an additional argument called `lowercols`, which defaults to `True` to keep the api the same, and make changes less disruptive. I have tested this and it works.
I was wondering if I should create some sort of warning here too saying how this argument will be deprecated in the next release after this one, and the `*values` dataframe will default to columns similar to the model in future releases, therefore user have to add `lowercase=False` to anticipate for that?
> Make lowercase columns default, add option to make them same as model

- .travis.yml
- odm2api/ODM2/services/readService.py
Added eager loading for samplingfeaturedataset to try and cut down on query time.
> Samplingfeaturedataset dev

- .travis.yml
- appveyor.yml
@lsetiawan and @emiliom this PR makes use of the conda-forge version of the odm2 packages.
> use conda-forge

- README.md
- docs/source/installing.rst
Update README to reflect changes to `conda-forge` channel and how to install the latest development version.
> Update README DOCS

- odm2api/services/readService.py
- tests/test_odm2/test_readservice.py
Addresses results in https://travis-ci.org/ODM2/ODM2PythonAPI/jobs/522572825
> Coding standards improvements

- tests/test_SessionFactory.py
- tests/test_connection.py
- tests/test_odm2/test_createservice.py
- tests/test_odm2/test_model.py
- tests/test_odm2/test_odm2.py
Updated all cases of the use of deprecated ODM2 module hierarchy reported in the TravisCI log
> Updated odm2api module path calls in tests/test_odm2 modules to remove deprecated use of ODM2 module hierarchy
